---

- name: enable EPEL repository
  yum: name=epel-release state=present

- name: install system utilities
  yum:
    name:
      - unzip
      - rsync
      - git
      - bzip2
      - which
    state: present

- name: install virtualenv
  command: /usr/local/bin/pip{{ cadd_rest_api_server_python_version }} install virtualenv
  args:
    creates: /usr/bin/virtualenv
  changed_when: false  # hack, might go to /usr/local/bin if Python is there...
