---

- name: define distribution-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: perform installation
  include_tasks: install/{{ ansible_os_family }}.yml

- include_tasks: cadd_rest_api.yml
- include_tasks: cadd_scripts.yml
